#Naive Bayes Algorithm-
 Bayes' TheoremAt its heart, the algorithm is just an application of Bayes' Theorem. This theorem allows us to update our beliefs based on new evidence.The general formula is:$$P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}$$In the context of machine learning, we swap $A$ and $B$ for things we care about: $y$ (the target class, like "Spam" or "Not Spam") and $X$ (the features or data points).$$P(y|X) = \frac{P(X|y) \cdot P(y)}{P(X)}$$

In [189]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [190]:
X,y = load_iris(return_X_y=True)

In [191]:
X
#Use Gaussian NB if independent features are continuous variables.

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [192]:
#multiclass classification-
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [193]:
#train-test split-
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [194]:
from sklearn.naive_bayes import GaussianNB

In [195]:
gnb = GaussianNB()
from sklearn.model_selection import GridSearchCV

In [196]:
gnb.fit(X_train,y_train)

GaussianNB()

In [197]:
y_pred = gnb.predict(X_test)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [198]:
gnb.predict_proba(X_test)

array([[4.15880005e-088, 9.95527834e-001, 4.47216606e-003],
       [1.00000000e+000, 1.31031235e-013, 2.21772205e-020],
       [9.83170191e-285, 2.70138564e-012, 1.00000000e+000],
       [9.54745274e-092, 9.74861431e-001, 2.51385686e-002],
       [1.08679560e-103, 8.31910700e-001, 1.68089300e-001],
       [1.00000000e+000, 6.77693844e-013, 7.14891338e-021],
       [2.79985841e-051, 9.99963925e-001, 3.60749274e-005],
       [3.47130487e-172, 4.26099520e-007, 9.99999574e-001],
       [8.87424368e-094, 9.93578115e-001, 6.42188515e-003],
       [1.01525828e-057, 9.99952885e-001, 4.71152410e-005],
       [3.89708229e-148, 2.58773323e-004, 9.99741227e-001],
       [1.00000000e+000, 1.41103765e-016, 9.36331484e-025],
       [1.00000000e+000, 2.50761563e-016, 5.99383407e-024],
       [1.00000000e+000, 3.02382725e-016, 3.69654979e-024],
       [1.00000000e+000, 2.31820777e-016, 1.18856457e-023],
       [6.09343428e-105, 4.23901472e-001, 5.76098528e-001],
       [8.42661111e-199, 2.69249362e-007

In [199]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

accuracy_score(y_test,y_pred)

0.9777777777777777

In [200]:
confusion_matrix(y_test,y_pred)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]])

In [201]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        19\n           1       1.00      0.92      0.96        13\n           2       0.93      1.00      0.96        13\n\n    accuracy                           0.98        45\n   macro avg       0.98      0.97      0.97        45\nweighted avg       0.98      0.98      0.98        45\n'

#Parameters for Hyperparameter Tuning in Gaussian NB-

1. Var Smoothing- (The Variance Stabilizer)By default, Scikit-Learn sets var_smoothing to $10^{-9}$ ($1\times 10^{-9}$). This is the primary hyperparameter tuned during cross-validation.The Problem It Solves: Gaussian NB assumes your features follow a normal distribution (bell curve). If a sample in your test dataset is far away from the training data mean, its calculated probability can drop to absolute zero. Because Naive Bayes multiplies the probabilities of all features together, a single zero will zero out the entire calculation, destroying the model's ability to make a prediction.How It Works: var_smoothing artificially expands the variance of all features by adding a fraction of the maximum variance found in the dataset to every feature's variance.The Impact: It acts as a regularization parameter. Increasing var_smoothing flattens and widens the Gaussian curves. This makes the model less sensitive to extreme outliers and forces it to be more conservative (less confident) in its predictions.


2. Priors: (The Class Weights)By default, Scikit-Learn sets priors=None. This means the algorithm automatically calculates the prior probabilities directly from your training data based on class frequency. For example, if your training data contains 70% Class A and 30% Class B, the priors are automatically set to $P(A) = 0.7$ and $P(B) = 0.3$.Why Tune It? You manually pass an array of probabilities (e.g., priors=[0.5, 0.5]) if you want to override the dataset's natural distribution.When To Use It: * Imbalanced Datasets: If your training data is heavily skewed (e.g., 99% legitimate emails, 1% fraud), the model will have a massive bias toward predicting the majority class. Manually adjusting the priors to be equal ($0.5 / 0.5$) forces the model to penalize misclassifications of the minority class more severely.Domain Knowledge: If you know ahead of time that the real-world deployment environment will have a different class distribution than your training set, you can set the expected priors manually.

In [202]:
#Hyperparameter tuning-
from sklearn.model_selection import GridSearchCV

# 4. Define the hyperparameter grid
param_grid = {
    'var_smoothing': np.logspace(0, -9, num=50),
    'priors': [None, [0.3, 0.7], [0.2, 0.8]]
}

# 3. Set up GridSearchCV
grid_search = GridSearchCV(
    estimator=gnb,
    param_grid=param_grid,
    cv=5,   # 5-fold cross-validation
    scoring='accuracy',
    n_jobs=-1
)

# 4. Fit the data (Assuming you have X_train and y_train ready)
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
500 fits failed out of a total of 750.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/naive_bayes.py", line 266, in fit
    return self._partial_fit(
     

GridSearchCV(cv=5, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'priors': [None, [0.3, 0.7], [0.2, 0.8]],
                         'var_smoothing': array([1.00000000e+00, 6.55128557e-01, 4.29193426e-01, 2.81176870e-01,
       1.84206997e-01, 1.20679264e-01, 7.90604321e-02, 5.17947468e-02,
       3.39322177e-02, 2.22299648e-02, 1.45634848e-02, 9.54095476e-03,
       6.25055193e-03, 4.09491506e-03, 2.68269580e-03, 1.7...
       7.19685673e-06, 4.71486636e-06, 3.08884360e-06, 2.02358965e-06,
       1.32571137e-06, 8.68511374e-07, 5.68986603e-07, 3.72759372e-07,
       2.44205309e-07, 1.59985872e-07, 1.04811313e-07, 6.86648845e-08,
       4.49843267e-08, 2.94705170e-08, 1.93069773e-08, 1.26485522e-08,
       8.28642773e-09, 5.42867544e-09, 3.55648031e-09, 2.32995181e-09,
       1.52641797e-09, 1.00000000e-09])},
             scoring='accuracy')

In [203]:
grid_search.best_params_


{'priors': None, 'var_smoothing': np.float64(0.022229964825261943)}

In [204]:
grid_search.best_score_

np.float64(0.9333333333333333)

In [205]:
y_pred = grid_search.predict(X_test)

accuracy_score   = accuracy_score(y_test,y_pred)
classification_report = classification_report(y_test,y_pred)
confusion_matrix = confusion_matrix(y_test,y_pred)

print(accuracy_score)
print(classification_report)
print(confusion_matrix)

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]




### Why Naive Bayes Doesn't Need Standardization

**1. It Relies on Probability, Not Distance**
Standardization is crucial for algorithms that calculate the distance between data points (like K-Nearest Neighbors or Support Vector Machines) or algorithms that use gradient descent (like Neural Networks). Because Naive Bayes is a probabilistic classifier based on Bayes' Theorem, it doesn't measure spatial distances between features.

**2. The "Naive" Independence Assumption**
Naive Bayes assumes that every feature is completely independent of the others. When it calculates the probability of a data point belonging to a certain class, it evaluates each feature individually and then multiplies those probabilities together. Because the features are never directly weighed against each other in a combined formula, a feature with a scale of 1,000–10,000 will not "overpower" a feature with a scale of 0–1.

**3. The Math Balances Out (Gaussian Naive Bayes)**
If you are using Gaussian Naive Bayes for continuous data, the algorithm calculates the mean and variance for each feature within each class.

* If you input raw data, it uses the raw mean and raw variance to calculate the probability density.
* If you standardize the data, the mean becomes 0 and the variance becomes 1, and the probability density shifts accordingly.
Ultimately, the *relative* likelihoods between different classes remain exactly the same. Scaling changes the absolute numbers but doesn't change the final classification decision.

---

### When Standardization Can Actually Break Naive Bayes

In some variations of Naive Bayes, standardizing your data is not just unnecessary—it's actively harmful.

* **Multinomial Naive Bayes:** This variation is heavily used for text classification (like spam filtering) and relies on discrete counts (e.g., how many times a word appears in a document). Standardizing this data usually introduces negative values. Multinomial Naive Bayes **cannot handle negative values** because a negative frequency count doesn't make mathematical sense.
* **Sparse Data:** Text data is usually represented in sparse matrices (mostly zeros). Standardizing forces the data to be centered around zero, which converts all those meaningful zeros into non-zero floats. This destroys the sparsity, demanding massive amounts of memory and completely ruining computational efficiency.

### Summary

Save your preprocessing steps! You can safely feed your raw, unscaled features directly into a Naive Bayes model. Save standardization for algorithms like KNN, SVM, PCA, or Logistic Regression.

## K-Nearest Neighbours-
Instance based learning model used for classification and regression.

In [206]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=1000, # 1000 observations
    n_features=3, # 3 total features
    n_redundant=1,
    n_classes=2, # binary target/label
    random_state=999
)


In [207]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [208]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [41]:
from sklearn.neighbors import KNeighborsClassifier

#p = 1 (manhattan distance)
#p = 2 (euclidean distance)

#algorithm- ball tree ,kdtree,brute
#kdtree,ball tree will create a binary tree (Time complexity reduced wrt search)
#auto-

#weights-{uniform and distance}

knn = KNeighborsClassifier(n_neighbors=6,p=2,algorithm='auto',weights='uniform')
knn.fit(X_train,y_train)
#features that are randomly distributed in feature dimensions-euclidean distance

KNeighborsClassifier(n_neighbors=6)

## Hyperparameters for KNN-
1)Use Euclidean for continuous, low-dimensional data, and use Manhattan for high-dimensional data, sparse data, or when your dataset has many outliers.


 2) K-D Tree: Best for Low Dimensions ($D < 20$)How it works: It recursively slices your data space into a grid of hyper-rectangles using straight, axis-aligned cuts.When to use it: When you have fewer than 20 features/dimensions.Why it fails later: As you add more dimensions, the volume of those rectangles grows exponentially. The algorithm ends up having to search through almost every single "box" to find the true nearest neighbor, completely defeating the purpose of the tree. This is the "curse of dimensionality."2. Ball Tree: Best for High Dimensions ($D \ge 20$)How it works: It organizes data into a nested series of overlapping hyper-spheres (balls) rather than boxes.When to use it: When you have 20 or more features/dimensions.Why it works better here: Spheres don't have corners. In high-dimensional space, calculating the distance between spheres allows the algorithm to rule out large chunks of data much more efficiently than checking the corners of axis-aligned boxes.

 3) n_neighbours - The number of neighbouring pts estimated for predicting outcome of a new scoring point.

In [42]:
y_pred = knn.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

accuracy_score(y_test,y_pred)
classification_report(y_test,y_pred)
confusion_matrix(y_test,y_pred)

array([[144,  10],
       [ 23, 123]])

In [44]:
accuracy_score(y_test,y_pred)

0.89

In [62]:
from sklearn.model_selection import GridSearchCV, train_test_split
param_grid = {
    'n_neighbors': [i for i in range(1,11)],
    'metric': ['euclidean', 'manhattan'],  # Testing distance metrics
    'algorithm': ['kd_tree', 'ball_tree']  # Testing spatial tree algorithms
}

grid_search = GridSearchCV(
    estimator=knn,
    param_grid=param_grid,
    cv=5,          # 5-fold cross-validation
    scoring='accuracy',
    n_jobs=-1      # Use all available CPU cores to speed it up
)

print("Running GridSearchCV... testing all 20 combinations...")
grid_search.fit(X_train, y_train)


Running GridSearchCV... testing all 20 combinations...


GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=6), n_jobs=-1,
             param_grid={'algorithm': ['kd_tree', 'ball_tree'],
                         'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [63]:
# Output the best results
print("\n--- Best Model Found ---")
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best Cross-Validation Accuracy: {grid_search.best_score_:.4f}")

# 8. Final evaluation on the unseen test set
test_accuracy = grid_search.score(X_test, y_test)
print(f"Final Test Set Accuracy: {test_accuracy:.4f}")


--- Best Model Found ---
Best Parameters: {'algorithm': 'kd_tree', 'metric': 'manhattan', 'n_neighbors': 9}
Best Cross-Validation Accuracy: 0.9014
Final Test Set Accuracy: 1.0000


In [68]:
y_test = grid_search.predict(X_test)

In [69]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

accuracy_score(y_test,y_pred)
classification_report(y_test,y_pred)
confusion_matrix(y_test,y_pred)

array([[158,   0],
       [  9, 133]])

In [70]:
print(accuracy_score(y_test,y_pred))

0.97


KNN regressor

In [77]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [78]:
X,y = make_regression(n_samples=1000,n_features=2,noise=10,random_state=42)


In [84]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [85]:
regressor = KNeighborsRegressor()
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [86]:
y_pred = regressor.predict(X_test)

In [87]:
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))



133.35069426462292
0.9172710669776581
133.35069426462292
9.305447831862232


In [93]:
param_grid = {
    'n_neighbors': [i for i in range(2,11)],
    'metric': ['euclidean', 'manhattan'],  # Testing distance metrics
    'algorithm': ['kd_tree', 'ball_tree']  # Testing spatial tree algorithms
}

grid_search = GridSearchCV(
    estimator=regressor,
    param_grid=param_grid,
    cv=5,          # 5-fold cross-validation
    scoring='accuracy',
    n_jobs=-1      # Use all available CPU cores to speed it up
)

print("Running GridSearchCV... testing all 20 combinations...")
grid_search.fit(X_train, y_train)

Running GridSearchCV... testing all 20 combinations...


/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(


GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'algorithm': ['kd_tree', 'ball_tree'],
                         'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [94]:
y_pred = grid_search.predict(X_test)

In [95]:
grid_search.best_params_

{'algorithm': 'kd_tree', 'metric': 'euclidean', 'n_neighbors': 2}

In [96]:
grid_search.best_score_

np.float64(nan)

In [97]:
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

164.32339389090953
0.8980560309627766
164.32339389090953
10.379310620857094
